// frontend/src/app/shared/components/button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';

@Component({
  selector: 'app-button',
  standalone: true,
  imports: [CommonModule],
  template: `
    <button
      [type]="type"
      [disabled]="disabled"
      (click)="onClick.emit($event)"
      [ngClass]="getClasses()"
      class="inline-flex items-center justify-center font-medium rounded-md transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2"
    >
      <ng-content></ng-content>
    </button>
  `
})
export class ButtonComponent {
  @Input() variant: ButtonVariant = 'primary';
  @Input() type: 'button' | 'submit' | 'reset' = 'button';
  @Input() disabled = false;
  @Input() customClass = '';
  @Output() onClick = new EventEmitter<MouseEvent>();

  getClasses(): string {
    const baseClasses = 'px-4 py-2 ';
    let variantClasses = '';
    
    switch (this.variant) {
      case 'primary':
        variantClasses = 'bg-primary text-text-inverse hover:bg-primary-dark focus:ring-primary';
        break;
      case 'secondary':
        variantClasses = 'bg-card-bg text-text-primary border border-border hover:bg-bg-surface focus:ring-secondary';
        break;
      case 'ghost':
        variantClasses = 'bg-transparent text-text-secondary hover:text-text-primary hover:bg-bg-surface focus:ring-border';
        break;
      case 'danger':
        variantClasses = 'bg-error text-text-inverse hover:opacity-90 focus:ring-error';
        break;
    }
    
    const disabledClasses = this.disabled ? 'opacity-50 cursor-not-allowed ' : '';
    
    return baseClasses + variantClasses + ' ' + disabledClasses + this.customClass;
  }
}

// frontend/src/components/ui/Button.tsx
import type React from "react"
import type { ButtonHTMLAttributes } from "react"

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary" | "outline"
  size?: "sm" | "md" | "lg"
  isLoading?: boolean
  children: React.ReactNode
}

const Button: React.FC<ButtonProps> = ({
  variant = "primary",
  size = "md",
  isLoading = false,
  children,
  className = "",
  disabled,
  ...props
}) => {
  const baseClasses =
    "font-semibold rounded-full transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-opacity-50"

  const variantClasses = {
    primary: "bg-yellow-400 text-gray-800 hover:bg-yellow-500 focus:ring-yellow-400",
    secondary: "bg-gray-600 text-white hover:bg-gray-700 focus:ring-gray-500",
    outline: "border-2 border-white text-white hover:bg-white hover:text-gray-800 focus:ring-white",
  }

  const sizeClasses = {
    sm: "px-4 py-2 text-sm",
    md: "px-6 py-3 text-base",
    lg: "px-8 py-4 text-lg",
  }

  const isDisabled = disabled || isLoading

  return (
    <button
      className={`
        ${baseClasses}
        ${variantClasses[variant]}
        ${sizeClasses[size]}
        ${isDisabled ? "opacity-50 cursor-not-allowed" : "cursor-pointer"}
        ${className}
      `}
      disabled={isDisabled}
      {...props}
    >
      {isLoading ? (
        <div className="flex items-center justify-center">
          <div className="animate-spin rounded-full h-4 w-4 border-2 border-current border-t-transparent mr-2"></div>
          Cargando...
        </div>
      ) : (
        children
      )}
    </button>
  )
}

export { Button }
export default Button
