// frontend/src/app/shared/components/button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';

@Component({
  selector: 'app-button',
  standalone: true,
  imports: [CommonModule],
  template: `
    <button
      [type]="type"
      [disabled]="disabled"
      (click)="onClick.emit($event)"
      [ngClass]="getClasses()"
      class="inline-flex items-center justify-center font-medium rounded-md transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2"
    >
      <ng-content></ng-content>
    </button>
  `
})
export class ButtonComponent {
  @Input() variant: ButtonVariant = 'primary';
  @Input() type: 'button' | 'submit' | 'reset' = 'button';
  @Input() disabled = false;
  @Input() customClass = '';
  @Output() onClick = new EventEmitter<MouseEvent>();

  getClasses(): string {
    const baseClasses = 'px-4 py-2 ';
    let variantClasses = '';
    
    switch (this.variant) {
      case 'primary':
        variantClasses = 'bg-primary text-text-inverse hover:bg-primary-dark focus:ring-primary';
        break;
      case 'secondary':
        variantClasses = 'bg-card-bg text-text-primary border border-border hover:bg-bg-surface focus:ring-secondary';
        break;
      case 'ghost':
        variantClasses = 'bg-transparent text-text-secondary hover:text-text-primary hover:bg-bg-surface focus:ring-border';
        break;
      case 'danger':
        variantClasses = 'bg-error text-text-inverse hover:opacity-90 focus:ring-error';
        break;
    }
    
    const disabledClasses = this.disabled ? 'opacity-50 cursor-not-allowed ' : '';
    
    return baseClasses + variantClasses + ' ' + disabledClasses + this.customClass;
  }
}

// Frontend/src/components/atoms/Button.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react';

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  children: ReactNode;
  variant?: 'primary' | 'secondary' | 'danger';
  size?: 'sm' | 'md' | 'lg';
}

/**
 * Button atom component
 * Basic reusable button component with variants
 * Follows Design System Guide: violet-600 for primary, rounded-xl
 */
export const Button = ({
  children,
  variant = 'primary',
  size = 'md',
  className = '',
  disabled,
  ...props
}: ButtonProps) => {
  const baseStyles =
    'font-medium rounded-xl transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center';

  const variants = {
    primary:
      'bg-violet-600 text-white hover:bg-violet-700 focus:ring-violet-500 active:bg-violet-800',
    secondary: 'bg-slate-200 text-slate-900 hover:bg-slate-300 focus:ring-slate-500',
    danger: 'bg-red-500 text-white hover:bg-red-600 focus:ring-red-500',
  };

  const sizes = {
    sm: 'px-3 py-1.5 text-sm min-h-[36px]',
    md: 'px-4 py-2 text-base min-h-[44px]',
    lg: 'px-6 py-3 text-lg h-12', // h-12 = 48px as per Design System Guide
  };

  return (
    <button
      type="button"
      className={`${baseStyles} ${variants[variant]} ${sizes[size]} ${className}`}
      disabled={disabled}
      {...props}
    >
      {children}
    </button>
  );
};
